'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Department
    Public Property DepartmentID As Integer
    Public Property Name As String
    Public Property Budget As Decimal
    Public Property StartDate As Date
    Public Property Administrator As Nullable(Of Integer)

    Public Overridable Property Courses As ICollection(Of Course) = New HashSet(Of Course)

End Class
