'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OnsiteCourse
    Public Property CourseID As Integer
    Public Property Location As String
    Public Property Days As String
    Public Property Time As Date

    Public Overridable Property Course As Course

End Class
