'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Person
    Public Property PersonID As Integer
    Public Property LastName As String
    Public Property FirstName As String
    Public Property HireDate As Nullable(Of Date)
    Public Property EnrollmentDate As Nullable(Of Date)

    Public Overridable Property OfficeAssignment As OfficeAssignment
    Public Overridable Property StudentGrades As ICollection(Of StudentGrade) = New HashSet(Of StudentGrade)
    Public Overridable Property Courses As ICollection(Of Course) = New HashSet(Of Course)

End Class
