'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StudentGrade
    Public Property EnrollmentID As Integer
    Public Property CourseID As Integer
    Public Property StudentID As Integer
    Public Property Grade As Nullable(Of Decimal)

    Public Overridable Property Course As Course
    Public Overridable Property Person As Person

End Class
